namespace auernautica_imperiali {
    public enum EWeaponType {
        QUADBIGSHOOTAS, TURRETBIGSHOOTAS, TAILGUN, PORTTURRET, STARBOARDTURRET, GROTBOMMS, LASCANNON, DORSALTURRET, REARTURRET, BOMBBAY, TWINMULITLASERS, QUADAUTOCANNON, TWINLASCANNON
    }
}